// prisma/seed.cjs
const dotenv = require("dotenv");

dotenv.config();

async function main() {
    // Import prisma client via dynamic import (ESM)
    const { default: prisma } = await import('../lib/prisma.js');

// ----- Products -----
    const productData = [
        { name: "Gaming Laptop", description: "High-performance gaming laptop with RTX 3080", price: 1500.00, qteInStock: 12 },
        { name: "Smartphone", description: "Latest Android smartphone with 128GB storage", price: 699.99, qteInStock: 25 },
        { name: "Wireless Headphones", description: "Noise-cancelling wireless headphones", price: 199.99, qteInStock: 20 },
        { name: "Smartwatch", description: "Fitness tracking smartwatch", price: 299.99, qteInStock: 15 },
        { name: "4K Monitor", description: "27-inch 4K UHD monitor", price: 399.99, qteInStock: 10 },
        { name: "Mechanical Keyboard", description: "RGB backlit mechanical keyboard", price: 129.99, qteInStock: 30 },
        { name: "Gaming Mouse", description: "Ergonomic gaming mouse with DPI adjustment", price: 79.99, qteInStock: 40 },
        { name: "External SSD", description: "1TB portable external SSD", price: 149.99, qteInStock: 18 },
        { name: "Bluetooth Speaker", description: "Portable waterproof Bluetooth speaker", price: 59.99, qteInStock: 50 },
        { name: "Webcam", description: "1080p HD webcam for video calls", price: 89.99, qteInStock: 22 },
        { name: "Tablet", description: "10-inch tablet with stylus support", price: 399.99, qteInStock: 14 },
        { name: "Router", description: "Dual-band WiFi router", price: 99.99, qteInStock: 16 },
        { name: "Printer", description: "All-in-one wireless printer", price: 249.99, qteInStock: 8 },
        { name: "Drone", description: "4K camera drone with GPS", price: 799.99, qteInStock: 6 },
        { name: "Fitness Tracker", description: "Heart rate and sleep monitoring fitness band", price: 49.99, qteInStock: 35 },
        { name: "E-reader", description: "6-inch e-reader with adjustable lighting", price: 149.99, qteInStock: 20 },
        { name: "Power Bank", description: "20,000mAh portable power bank", price: 39.99, qteInStock: 60 },
        { name: "Digital Camera", description: "DSLR camera with 18-55mm lens", price: 599.99, qteInStock: 9 },
        { name: "Laptop Stand", description: "Adjustable ergonomic laptop stand", price: 29.99, qteInStock: 45 },
        { name: "USB Hub", description: "7-port USB-C hub", price: 49.99, qteInStock: 28 },
        { name: "Gaming Chair", description: "Ergonomic gaming chair with lumbar support", price: 299.99, qteInStock: 15 },
        { name: "Microphone", description: "Professional USB microphone for streaming", price: 129.99, qteInStock: 22 },
        { name: "Graphics Tablet", description: "Digital drawing tablet with stylus", price: 199.99, qteInStock: 18 },
        { name: "Network Switch", description: "8-port gigabit network switch", price: 79.99, qteInStock: 25 },
        { name: "Cable Management", description: "Under desk cable management tray", price: 24.99, qteInStock: 40 },
        { name: "Desk Lamp", description: "LED desk lamp with adjustable brightness", price: 34.99, qteInStock: 30 },
        { name: "Monitor Stand", description: "Adjustable monitor stand with storage", price: 49.99, qteInStock: 20 },
        { name: "Mouse Pad", description: "Extended gaming mouse pad", price: 19.99, qteInStock: 50 },
        { name: "HDMI Cable", description: "High-speed HDMI cable 6ft", price: 12.99, qteInStock: 60 },
        { name: "Ethernet Cable", description: "Cat6 ethernet cable 10ft", price: 8.99, qteInStock: 70 },
        { name: "Phone Case", description: "Protective phone case with screen protector", price: 15.99, qteInStock: 80 },
        { name: "Charging Cable", description: "USB-C fast charging cable", price: 14.99, qteInStock: 90 },
        { name: "Screen Protector", description: "Tempered glass screen protector", price: 9.99, qteInStock: 100 },
        { name: "Wireless Charger", description: "Fast wireless charging pad", price: 29.99, qteInStock: 35 },
        { name: "Car Mount", description: "Car phone mount with dashboard holder", price: 22.99, qteInStock: 28 },
        { name: "Travel Adapter", description: "Universal travel power adapter", price: 39.99, qteInStock: 20 },
        { name: "Laptop Bag", description: "Protective laptop backpack with USB port", price: 59.99, qteInStock: 25 },
        { name: "Desk Organizer", description: "Bamboo desk organizer with drawers", price: 34.99, qteInStock: 30 },
        { name: "Paper Shredder", description: "Cross-cut paper shredder", price: 89.99, qteInStock: 12 },
        { name: "Label Maker", description: "Thermal label maker for office", price: 49.99, qteInStock: 18 },
        { name: "Whiteboard", description: "Magnetic whiteboard with markers", price: 79.99, qteInStock: 15 },
        { name: "Filing Cabinet", description: "Mobile filing cabinet with 3 drawers", price: 129.99, qteInStock: 8 },
        { name: "Office Chair", description: "Ergonomic office chair with armrests", price: 199.99, qteInStock: 10 },
        { name: "Bookshelf", description: "5-tier wooden bookshelf", price: 89.99, qteInStock: 16 },
        { name: "Storage Box", description: "Stackable plastic storage boxes", price: 24.99, qteInStock: 40 },
        { name: "Desk Mat", description: "Large waterproof desk mat", price: 19.99, qteInStock: 50 },
        { name: "Wall Clock", description: "Modern wall clock with silent movement", price: 29.99, qteInStock: 25 },
        { name: "Picture Frame", description: "Digital picture frame with WiFi", price: 79.99, qteInStock: 12 },
        { name: "Plant Pot", description: "Self-watering plant pot with drainage", price: 14.99, qteInStock: 35 },
        { name: "Air Purifier", description: "HEPA air purifier for small rooms", price: 149.99, qteInStock: 8 },
        { name: "Humidifier", description: "Ultrasonic cool mist humidifier", price: 39.99, qteInStock: 20 },
        { name: "Fan", description: "Oscillating tower fan with remote", price: 59.99, qteInStock: 15 },
        { name: "Space Heater", description: "Ceramic space heater with thermostat", price: 49.99, qteInStock: 18 },
        { name: "Electric Kettle", description: "Stainless steel electric kettle", price: 34.99, qteInStock: 30 },
        { name: "Coffee Maker", description: "Drip coffee maker with timer", price: 79.99, qteInStock: 12 },
        { name: "Toaster", description: "2-slice toaster with bagel setting", price: 29.99, qteInStock: 25 },
        { name: "Blender", description: "High-speed blender with 64oz jar", price: 99.99, qteInStock: 10 },
        { name: "Food Processor", description: "Multi-function food processor", price: 149.99, qteInStock: 8 },
        { name: "Slow Cooker", description: "6-quart programmable slow cooker", price: 59.99, qteInStock: 15 },
        { name: "Air Fryer", description: "5.8qt digital air fryer", price: 89.99, qteInStock: 12 },
        { name: "Mixer", description: "Stand mixer with 5-quart bowl", price: 299.99, qteInStock: 6 },
        { name: "Rice Cooker", description: "Programmable rice cooker with steamer", price: 49.99, qteInStock: 20 },
        { name: "Electric Grill", description: "Indoor electric grill with smokeless", price: 129.99, qteInStock: 10 },
        { name: "Vacuum Cleaner", description: "Cordless stick vacuum cleaner", price: 199.99, qteInStock: 8 },
        { name: "Steam Mop", description: "Chemical-free steam mop", price: 99.99, qteInStock: 12 },
        { name: "Iron", description: "Steam iron with anti-drip", price: 34.99, qteInStock: 30 },
        { name: "Washing Machine", description: "Portable compact washing machine", price: 299.99, qteInStock: 5 },
        { name: "Dryer", description: "Vented clothes dryer", price: 399.99, qteInStock: 4 },
        { name: "Dishwasher", description: "Countertop dishwasher", price: 349.99, qteInStock: 6 },
        { name: "Microwave", description: "Countertop microwave oven", price: 149.99, qteInStock: 10 },
        { name: "Mini Fridge", description: "Compact mini refrigerator", price: 199.99, qteInStock: 8 },
        { name: "Freezer", description: "Chest freezer with basket", price: 299.99, qteInStock: 4 },
        { name: "Ice Maker", description: "Portable ice maker machine", price: 179.99, qteInStock: 6 },
        { name: "Water Dispenser", description: "Hot and cold water dispenser", price: 149.99, qteInStock: 8 },
        { name: "Wine Cooler", description: "18-bottle wine cooler", price: 399.99, qteInStock: 3 },
        { name: "Beverage Fridge", description: "120-can beverage refrigerator", price: 249.99, qteInStock: 5 },
        { name: "Toaster Oven", description: "Convection toaster oven", price: 79.99, qteInStock: 12 },
        { name: "Pressure Cooker", description: "Electric pressure cooker 6qt", price: 99.99, qteInStock: 10 },
        { name: "Sous Vide", description: "Precision sous vide cooker", price: 129.99, qteInStock: 8 },
        { name: "Food Scale", description: "Digital kitchen food scale", price: 24.99, qteInStock: 35 },
        { name: "Meat Thermometer", description: "Digital instant read thermometer", price: 19.99, qteInStock: 40 },
        { name: "Cutting Board", description: "Bamboo cutting board set", price: 29.99, qteInStock: 30 },
        { name: "Knife Set", description: "Professional chef knife set", price: 149.99, qteInStock: 12 },
        { name: "Cookware Set", description: "Non-stick cookware set 10pc", price: 199.99, qteInStock: 8 },
        { name: "Bakeware Set", description: "Carbon steel bakeware set", price: 79.99, qteInStock: 15 },
        { name: "Dinnerware Set", description: "16-piece ceramic dinnerware set", price: 89.99, qteInStock: 10 },
        { name: "Glassware Set", description: "12-piece glassware set", price: 49.99, qteInStock: 20 },
        { name: "Flatware Set", description: "20-piece stainless steel flatware", price: 59.99, qteInStock: 15 },
        { name: "Storage Containers", description: "Glass food storage containers set", price: 39.99, qteInStock: 25 },
        { name: "Spice Rack", description: "Wall-mounted spice rack", price: 34.99, qteInStock: 18 },
        { name: "Pantry Organizer", description: "Stackable pantry bins", price: 29.99, qteInStock: 30 },
        { name: "Trash Can", description: "Motion sensor trash can", price: 79.99, qteInStock: 12 },
        { name: "Recycling Bin", description: "Dual compartment recycling bin", price: 59.99, qteInStock: 15 },
        { name: "Laundry Hamper", description: "Double laundry hamper with lid", price: 49.99, qteInStock: 20 },
        { name: "Shoe Rack", description: "3-tier shoe storage rack", price: 39.99, qteInStock: 25 },
        { name: "Coat Rack", description: "Wall-mounted coat rack with hooks", price: 29.99, qteInStock: 30 },
        { name: "Mirror", description: "Full-length wall mirror", price: 89.99, qteInStock: 10 },
        { name: "Wall Art", description: "Modern abstract wall art canvas", price: 129.99, qteInStock: 8 },
        { name: "Curtains", description: "Blackout curtains with grommets", price: 49.99, qteInStock: 20 },
        { name: "Rug", description: "Area rug 5x7 with non-slip backing", price: 149.99, qteInStock: 12 },
        { name: "Throw Pillows", description: "Decorative throw pillows set of 4", price: 39.99, qteInStock: 25 },
        { name: "Blanket", description: "Fleece throw blanket with sherpa", price: 34.99, qteInStock: 30 },
        { name: "Comforter", description: "All-season down alternative comforter", price: 89.99, qteInStock: 15 },
        { name: "Bed Sheets", description: "100% cotton bed sheet set", price: 79.99, qteInStock: 18 },
        { name: "Mattress Topper", description: "Memory foam mattress topper", price: 99.99, qteInStock: 12 },
        { name: "Pillows", description: "Set of 2 sleeping pillows", price: 49.99, qteInStock: 25 },
        { name: "Duvet Cover", description: "Reversible duvet cover set", price: 69.99, qteInStock: 20 },
        { name: "Mattress Protector", description: "Waterproof mattress protector", price: 39.99, qteInStock: 30 },
        { name: "Bed Frame", description: "Platform bed frame with headboard", price: 299.99, qteInStock: 8 },
        { name: "Nightstand", description: "Modern nightstand with drawer", price: 149.99, qteInStock: 12 },
        { name: "Dresser", description: "6-drawer bedroom dresser", price: 399.99, qteInStock: 6 },
        { name: "Wardrobe", description: "Freestanding wardrobe closet", price: 299.99, qteInStock: 4 },
        { name: "Vanity Table", description: "Makeup vanity with mirror and lights", price: 199.99, qteInStock: 8 },
        { name: "Ottoman", description: "Storage ottoman with tufted top", price: 129.99, qteInStock: 15 },
        { name: "Sofa", description: "3-seater fabric sofa with chaise", price: 899.99, qteInStock: 3 },
        { name: "Armchair", description: "Comfortable reading armchair", price: 399.99, qteInStock: 5 },
        { name: "Coffee Table", description: "Modern coffee table with storage", price: 249.99, qteInStock: 8 },
        { name: "End Table", description: "Set of 2 nesting end tables", price: 149.99, qteInStock: 12 },
        { name: "TV Stand", description: "Media console TV stand", price: 199.99, qteInStock: 10 },
        { name: "Bookcase", description: "Tall ladder bookcase", price: 179.99, qteInStock: 8 },
        { name: "Console Table", description: "Entryway console table", price: 229.99, qteInStock: 6 },
        { name: "Bar Stool", description: "Set of 2 counter height bar stools", price: 199.99, qteInStock: 8 },
        { name: "Dining Table", description: "Extendable dining table for 6", price: 599.99, qteInStock: 4 },
        { name: "Dining Chairs", description: "Set of 4 dining chairs", price: 399.99, qteInStock: 6 },
        { name: "Sideboard", description: "Buffet sideboard with cabinets", price: 449.99, qteInStock: 5 },
        { name: "Hutch", description: "China cabinet hutch", price: 699.99, qteInStock: 3 },
        { name: "Bench", description: "Entryway storage bench", price: 179.99, qteInStock: 8 },
        { name: "Luggage Rack", description: "Foldable luggage rack", price: 49.99, qteInStock: 15 },
        { name: "Jewelry Box", description: "Lockable jewelry box with mirror", price: 79.99, qteInStock: 12 },
        { name: "Safe", description: "Digital home security safe", price: 199.99, qteInStock: 8 },
        { name: "Fire Extinguisher", description: "Home fire extinguisher", price: 39.99, qteInStock: 20 },
        { name: "Smoke Detector", description: "Photoelectric smoke detector", price: 29.99, qteInStock: 25 },
        { name: "Carbon Monoxide Detector", description: "Digital CO alarm", price: 34.99, qteInStock: 20 },
        { name: "Doorbell Camera", description: "WiFi video doorbell camera", price: 149.99, qteInStock: 12 },
        { name: "Security Camera", description: "Outdoor security camera system", price: 299.99, qteInStock: 6 },
        { name: "Smart Lock", description: "Keyless entry smart lock", price: 199.99, qteInStock: 10 },
        { name: "Motion Sensor Light", description: "Solar powered motion sensor light", price: 39.99, qteInStock: 30 },
        { name: "Smart Thermostat", description: "WiFi programmable thermostat", price: 249.99, qteInStock: 8 },
        { name: "Smart Speaker", description: "Voice controlled smart speaker", price: 99.99, qteInStock: 15 },
        { name: "Smart Display", description: "7-inch smart display with camera", price: 129.99, qteInStock: 12 },
        { name: "Smart Bulb", description: "WiFi color changing smart bulb", price: 19.99, qteInStock: 40 },
        { name: "Smart Plug", description: "WiFi smart plug with energy monitoring", price: 14.99, qteInStock: 50 },
        { name: "Smart Switch", description: "WiFi dimmer smart switch", price: 34.99, qteInStock: 25 },
        { name: "Video Doorbell", description: "Battery powered video doorbell", price: 199.99, qteInStock: 10 },
        { name: "Smart Watch", description: "Fitness and health tracking smartwatch", price: 299.99, qteInStock: 15 },
        { name: "Fitness Band", description: "Activity and sleep tracking band", price: 79.99, qteInStock: 30 },
        { name: "Heart Rate Monitor", description: "Chest strap heart rate monitor", price: 89.99, qteInStock: 20 },
        { name: "Running Shoes", description: "Professional running shoes", price: 129.99, qteInStock: 25 },
        { name: "Yoga Mat", description: "Non-slip exercise yoga mat", price: 29.99, qteInStock: 40 },
        { name: "Dumbbells", description: "Adjustable weight dumbbells set", price: 199.99, qteInStock: 12 },
        { name: "Resistance Bands", description: "Set of 5 resistance bands", price: 24.99, qteInStock: 50 },
        { name: "Exercise Ball", description: "Anti-burst stability exercise ball", price: 34.99, qteInStock: 30 },
        { name: "Jump Rope", description: "Speed jump rope with bearings", price: 14.99, qteInStock: 60 },
        { name: "Foam Roller", description: "High-density foam roller", price: 24.99, qteInStock: 35 },
        { name: "Pull Up Bar", description: "Doorway mounted pull up bar", price: 39.99, qteInStock: 25 },
        { name: "Punching Bag", description: "Freestanding punching bag", price: 149.99, qteInStock: 10 },
        { name: "Treadmill", description: "Folding electric treadmill", price: 599.99, qteInStock: 5 },
        { name: "Exercise Bike", description: "Magnetic resistance exercise bike", price: 399.99, qteInStock: 8 },
        { name: "Rowing Machine", description: "Magnetic resistance rowing machine", price: 499.99, qteInStock: 4 },
        { name: "Elliptical Trainer", description: "Front drive elliptical trainer", price: 699.99, qteInStock: 3 },
        { name: "Weight Bench", description: "Adjustable weight bench", price: 149.99, qteInStock: 12 },
        { name: "Power Rack", description: "Multi-functional power rack", price: 499.99, qteInStock: 4 },
        { name: "Battle Ropes", description: "40ft battle ropes set", price: 79.99, qteInStock: 15 },
        { name: "Agility Ladder", description: "Speed agility training ladder", price: 19.99, qteInStock: 40 },
        { name: "Training Cones", description: "Set of 50 training cones", price: 29.99, qteInStock: 30 },
        { name: "Medicine Ball", description: "Weighted medicine ball set", price: 89.99, qteInStock: 20 },
        { name: "Kettlebells", description: "Cast iron kettlebell set", price: 149.99, qteInStock: 12 },
        { name: "Boxing Gloves", description: "Professional boxing gloves", price: 59.99, qteInStock: 25 },
        { name: "Mouthguard", description: "Custom fit sports mouthguard", price: 19.99, qteInStock: 50 },
        { name: "Sports Water Bottle", description: "Insulated sports water bottle", price: 24.99, qteInStock: 60 },
        { name: "Gym Bag", description: "Duffel gym bag with shoe compartment", price: 49.99, qteInStock: 30 },
        { name: "Towel", description: "Quick dry microfiber sports towel", price: 14.99, qteInStock: 80 },
        { name: "Shower Gel", description: "Refreshing body shower gel", price: 12.99, qteInStock: 100 },
        { name: "Shampoo", description: "Moisturizing hair shampoo", price: 14.99, qteInStock: 90 },
        { name: "Conditioner", description: "Repairing hair conditioner", price: 14.99, qteInStock: 90 },
        { name: "Soap", description: "Natural bar soap set", price: 9.99, qteInStock: 120 },
        { name: "Toothbrush", description: "Soft bristle toothbrush", price: 4.99, qteInStock: 150 },
        { name: "Toothpaste", description: "Fluoride toothpaste", price: 5.99, qteInStock: 140 },
        { name: "Deodorant", description: "Long lasting deodorant", price: 7.99, qteInStock: 130 },
        { name: "Razor", description: "5-blade razor with lubrication strip", price: 12.99, qteInStock: 100 },
        { name: "Shaving Cream", description: "Rich lather shaving cream", price: 8.99, qteInStock: 110 },
        { name: "Lotion", description: "Daily moisturizing body lotion", price: 10.99, qteInStock: 120 },
        { name: "Sunscreen", description: "Broad spectrum SPF 50 sunscreen", price: 15.99, qteInStock: 80 },
        { name: "Lip Balm", description: "Moisturizing lip balm with SPF", price: 3.99, qteInStock: 160 },
        { name: "Hand Sanitizer", description: "Alcohol based hand sanitizer", price: 4.99, qteInStock: 180 },
        { name: "Face Mask", description: "Disposable face masks pack", price: 9.99, qteInStock: 200 },
        { name: "Gloves", description: "Disposable nitrile gloves", price: 6.99, qteInStock: 150 },
        { name: "First Aid Kit", description: "Complete first aid kit", price: 29.99, qteInStock: 40 },
        { name: "Thermometer", description: "Digital oral thermometer", price: 12.99, qteInStock: 60 },
        { name: "Blood Pressure Monitor", description: "Automatic blood pressure monitor", price: 49.99, qteInStock: 25 },
        { name: "Pill Organizer", description: "Weekly pill organizer", price: 8.99, qteInStock: 80 },
        { name: "Vitamins", description: "Multivitamin supplement bottle", price: 19.99, qteInStock: 50 },
        { name: "Protein Powder", description: "Whey protein powder 2lb", price: 39.99, qteInStock: 35 },
        { name: "Energy Bars", description: "Protein energy bars box", price: 24.99, qteInStock: 60 },
        { name: "Water Filter", description: "Pitcher water filter system", price: 29.99, qteInStock: 40 },
        { name: "Water Bottle", description: "Stainless steel water bottle", price: 19.99, qteInStock: 70 },
        { name: "Lunch Box", description: "Bento lunch box set", price: 24.99, qteInStock: 50 },
        { name: "Food Container", description: "Microwave safe food containers", price: 14.99, qteInStock: 80 },
        { name: "Cutlery Set", description: "Reusable travel cutlery set", price: 12.99, qteInStock: 90 },
        { name: "Napkins", description: "Paper napkins pack", price: 4.99, qteInStock: 200 },
        { name: "Paper Towels", description: "Paper towels roll pack", price: 12.99, qteInStock: 100 },
        { name: "Trash Bags", description: "Kitchen trash bags box", price: 15.99, qteInStock: 80 },
        { name: "Cleaning Spray", description: "All-purpose cleaner spray", price: 6.99, qteInStock: 120 },
        { name: "Sponges", description: "Non-scratch cleaning sponges", price: 5.99, qteInStock: 150 },
        { name: "Dish Soap", description: "Concentrated dish soap", price: 4.99, qteInStock: 180 },
        { name: "Laundry Detergent", description: "Liquid laundry detergent", price: 12.99, qteInStock: 100 },
        { name: "Fabric Softener", description: "Liquid fabric softener", price: 8.99, qteInStock: 110 },
        { name: "Dryer Sheets", description: "Anti-static dryer sheets", price: 7.99, qteInStock: 130 },
        { name: "Stain Remover", description: "Spray stain remover", price: 9.99, qteInStock: 90 },
        { name: "Bleach", description: "Household bleach liquid", price: 4.99, qteInStock: 120 },
        { name: "Glass Cleaner", description: "Ammonia free glass cleaner", price: 5.99, qteInStock: 140 },
        { name: "Floor Cleaner", description: "Multi-surface floor cleaner", price: 8.99, qteInStock: 100 },
        { name: "Mop", description: "Spin mop and bucket system", price: 39.99, qteInStock: 30 },
        { name: "Broom", description: "Angle broom with dustpan", price: 19.99, qteInStock: 60 },
        { name: "Dustpan", description: "Handheld dustpan", price: 7.99, qteInStock: 100 },
        { name: "Bucket", description: "5-gallon utility bucket", price: 9.99, qteInStock: 80 },
        { name: "Gloves", description: "Rubber cleaning gloves", price: 6.99, qteInStock: 120 },
        { name: "Scrub Brush", description: "Handheld scrub brush", price: 5.99, qteInStock: 150 },
        { name: "Squeegee", description: "Window and shower squeegee", price: 8.99, qteInStock: 80 },
        { name: "Plunger", description: "Heavy duty toilet plunger", price: 12.99, qteInStock: 60 },
        { name: "Toilet Brush", description: "Toilet brush with holder", price: 9.99, qteInStock: 90 },
        { name: "Shower Head", description: "High pressure shower head", price: 34.99, qteInStock: 40 },
        { name: "Faucet", description: "Kitchen sink faucet", price: 149.99, qteInStock: 20 },
        { name: "Sink", description: "Stainless steel kitchen sink", price: 299.99, qteInStock: 10 },
        { name: "Toilet", description: "Dual flush toilet", price: 249.99, qteInStock: 12 },
        { name: "Bathroom Vanity", description: "48 inch bathroom vanity", price: 499.99, qteInStock: 6 },
        { name: "Mirror", description: "LED bathroom mirror", price: 199.99, qteInStock: 15 },
        { name: "Towel Rack", description: "Wall mounted towel rack", price: 29.99, qteInStock: 40 },
        { name: "Toilet Paper Holder", description: "Wall mounted toilet paper holder", price: 19.99, qteInStock: 60 },
        { name: "Soap Dispenser", description: "Automatic soap dispenser", price: 24.99, qteInStock: 50 },
        { name: "Toothbrush Holder", description: "Countertop toothbrush holder", price: 12.99, qteInStock: 80 },
        { name: "Shower Curtain", description: "Waterproof shower curtain", price: 19.99, qteInStock: 70 },
        { name: "Bath Mat", description: "Memory foam bath mat", price: 24.99, qteInStock: 60 },
        { name: "Shower Caddy", description: "Corner shower caddy", price: 29.99, qteInStock: 40 },
        { name: "Bath Towels", description: "Set of 4 bath towels", price: 39.99, qteInStock: 30 },
        { name: "Hand Towels", description: "Set of 4 hand towels", price: 19.99, qteInStock: 50 },
        { name: "Washcloths", description: "Set of 6 washcloths", price: 14.99, qteInStock: 70 },
        { name: "Robe", description: "Plush bath robe", price: 49.99, qteInStock: 25 },
        { name: "Slippers", description: "Memory foam slippers", price: 29.99, qteInStock: 40 },
        { name: "Hair Dryer", description: "Ionic hair dryer", price: 59.99, qteInStock: 30 },
        { name: "Straightener", description: "Ceramic hair straightener", price: 49.99, qteInStock: 35 },
        { name: "Curling Iron", description: "Professional curling iron", price: 39.99, qteInStock: 40 },
        { name: "Electric Shaver", description: "Rotary electric shaver", price: 79.99, qteInStock: 20 },
        { name: "Trimmer", description: "Beard and mustache trimmer", price: 34.99, qteInStock: 45 },
        { name: "Nail Clippers", description: "Stainless steel nail clippers", price: 8.99, qteInStock: 100 },
        { name: "Tweezers", description: "Precision tweezers", price: 6.99, qteInStock: 120 },
        { name: "Nail File", description: "Emery nail file set", price: 4.99, qteInStock: 150 },
        { name: "Cotton Balls", description: "Cotton balls container", price: 5.99, qteInStock: 140 },
        { name: "Q-Tips", description: "Cotton swabs box", price: 4.99, qteInStock: 180 },
        { name: "Makeup Remover", description: "Makeup remover wipes", price: 7.99, qteInStock: 100 },
        { name: "Face Wash", description: "Gentle face wash cleanser", price: 12.99, qteInStock: 80 },
        { name: "Moisturizer", description: "Daily face moisturizer", price: 18.99, qteInStock: 70 },
        { name: "Eye Cream", description: "Anti-aging eye cream", price: 29.99, qteInStock: 50 },
        { name: "Serum", description: "Vitamin C face serum", price: 34.99, qteInStock: 45 },
        { name: "Face Mask", description: "Hydrating face mask pack", price: 19.99, qteInStock: 90 },
        { name: "Toner", description: "Balancing face toner", price: 16.99, qteInStock: 75 },
        { name: "Exfoliator", description: "Face exfoliating scrub", price: 14.99, qteInStock: 85 },
        { name: "Lip Balm", description: "Moisturizing lip balm", price: 5.99, qteInStock: 120 },
        { name: "Lipstick", description: "Long lasting lipstick", price: 19.99, qteInStock: 60 },
        { name: "Mascara", description: "Volumizing mascara", price: 15.99, qteInStock: 70 },
        { name: "Eyeliner", description: "Liquid eyeliner pen", price: 12.99, qteInStock: 80 },
        { name: "Foundation", description: "Liquid foundation makeup", price: 24.99, qteInStock: 65 },
        { name: "Concealer", description: "Full coverage concealer", price: 18.99, qteInStock: 75 },
        { name: "Blush", description: "Powder blush compact", price: 16.99, qteInStock: 85 },
        { name: "Eyeshadow", description: "Eyeshadow palette", price: 29.99, qteInStock: 55 },
        { name: "Makeup Brushes", description: "Professional makeup brush set", price: 39.99, qteInStock: 40 },
        { name: "Makeup Bag", description: "Cosmetic makeup bag", price: 19.99, qteInStock: 70 },
        { name: "Perfume", description: "Designer perfume bottle", price: 79.99, qteInStock: 30 },
        { name: "Cologne", description: "Men's cologne spray", price: 69.99, qteInStock: 35 },
        { name: "Body Spray", description: "Body spray deodorant", price: 12.99, qteInStock: 100 },
        { name: "Aftershave", description: "Soothing aftershave balm", price: 19.99, qteInStock: 60 },
        { name: "Shaving Cream", description: "Rich shaving cream", price: 14.99, qteInStock: 80 },
        { name: "Razor Blades", description: "Replacement razor blades", price: 18.99, qteInStock: 70 },
        { name: "Beard Oil", description: "Beard grooming oil", price: 22.99, qteInStock: 50 },
        { name: "Hair Gel", description: "Strong hold hair gel", price: 12.99, qteInStock: 90 },
        { name: "Hair Spray", description: "Flexible hold hair spray", price: 10.99, qteInStock: 100 },
        { name: "Hair Wax", description: "Matte hair styling wax", price: 14.99, qteInStock: 85 },
        { name: "Hair Pomade", description: "Classic hair pomade", price: 16.99, qteInStock: 75 },
        { name: "Sea Salt Spray", description: "Texturizing sea salt spray", price: 18.99, qteInStock: 65 },
        { name: "Hair Serum", description: "Frizz control hair serum", price: 24.99, qteInStock: 55 },
        { name: "Leave In Conditioner", description: "Leave in hair conditioner", price: 14.99, qteInStock: 80 },
        { name: "Hair Mask", description: "Deep conditioning hair mask", price: 19.99, qteInStock: 70 },
        { name: "Scalp Treatment", description: "Revitalizing scalp treatment", price: 29.99, qteInStock: 45 },
        { name: "Hair Vitamins", description: "Hair growth supplement vitamins", price: 24.99, qteInStock: 60 },
        { name: "Hair Color", description: "Permanent hair color kit", price: 12.99, qteInStock: 90 },
        { name: "Hair Bleach", description: "Hair lightening bleach kit", price: 15.99, qteInStock: 75 },
        { name: "Hair Toner", description: "Hair color toner", price: 18.99, qteInStock: 65 },
        { name: "Hair Developer", description: "Hair color developer", price: 8.99, qteInStock: 100 },
        { name: "Hair Foil", description: "Hair coloring foil sheets", price: 12.99, qteInStock: 85 },
        { name: "Hair Clips", description: "Sectioning hair clips set", price: 9.99, qteInStock: 120 },
        { name: "Hair Ties", description: "Elastic hair ties pack", price: 5.99, qteInStock: 150 },
        { name: "Headbands", description: "Sports headbands pack", price: 8.99, qteInStock: 110 },
        { name: "Hair Extensions", description: "Clip in hair extensions", price: 49.99, qteInStock: 40 },
        { name: "Wig", description: "Synthetic hair wig", price: 79.99, qteInStock: 25 },
        { name: "Hairpiece", description: "Hair topper piece", price: 59.99, qteInStock: 30 },
        { name: "Bangs", description: "Clip in bangs", price: 29.99, qteInStock: 50 },
        { name: "Hair Wrap", description: "Hair drying wrap turban", price: 19.99, qteInStock: 70 },
        { name: "Hair Towel", description: "Microfiber hair towel", price: 15.99, qteInStock: 80 },
        { name: "Hair Cap", description: "Shower hair cap", price: 7.99, qteInStock: 120 },
        { name: "Hair Net", description: "Disposable hair nets", price: 4.99, qteInStock: 200 },
        { name: "Hair Brush", description: "Paddle hair brush", price: 12.99, qteInStock: 90 },
        { name: "Comb", description: "Wide tooth comb", price: 6.99, qteInStock: 130 },
        { name: "Hair Pick", description: "Afro hair pick", price: 8.99, qteInStock: 100 },
        { name: "Round Brush", description: "Round styling brush", price: 14.99, qteInStock: 75 },
        { name: "Vent Brush", description: "Vent hair brush", price: 10.99, qteInStock: 85 },
        { name: "Teasing Brush", description: "Backcombing teasing brush", price: 12.99, qteInStock: 80 },
        { name: "Boar Bristle Brush", description: "Boar bristle brush", price: 18.99, qteInStock: 65 },
        { name: "Detangling Brush", description: "Detangling hair brush", price: 16.99, qteInStock: 70 },
        { name: "Scalp Brush", description: "Scalp exfoliating brush", price: 14.99, qteInStock: 75 },
        { name: "Shaving Brush", description: "Badger hair shaving brush", price: 29.99, qteInStock: 40 },
        { name: "Powder Brush", description: "Face powder brush", price: 22.99, qteInStock: 55 },
        { name: "Blush Brush", description: "Blush application brush", price: 18.99, qteInStock: 60 },
        { name: "Foundation Brush", description: "Liquid foundation brush", price: 20.99, qteInStock: 58 },
        { name: "Concealer Brush", description: "Concealer blending brush", price: 16.99, qteInStock: 62 },
        { name: "Eyebrow Brush", description: "Eyebrow shaping brush", price: 12.99, qteInStock: 75 },
        { name: "Eyelash Curler", description: "Eyelash curler tool", price: 15.99, qteInStock: 70 },
        { name: "Eyebrow Tweezers", description: "Precision eyebrow tweezers", price: 10.99, qteInStock: 85 },
        { name: "Eyebrow Scissors", description: "Eyebrow trimming scissors", price: 12.99, qteInStock: 80 },
        { name: "Eyebrow Razor", description: "Eyebrow shaping razor", price: 8.99, qteInStock: 100 },
        { name: "Eyebrow Pencil", description: "Eyebrow defining pencil", price: 14.99, qteInStock: 75 },
        { name: "Eyebrow Gel", description: "Eyebrow setting gel", price: 16.99, qteInStock: 65 },
        { name: "Eyebrow Powder", description: "Eyebrow filling powder", price: 18.99, qteInStock: 60 },
        { name: "Eyebrow Wax", description: "Eyebrow styling wax", price: 15.99, qteInStock: 70 },
        { name: "Eyebrow Stencil", description: "Eyebrow shaping stencil", price: 9.99, qteInStock: 90 },
        { name: "Eyebrow Kit", description: "Complete eyebrow kit", price: 29.99, qteInStock: 45 },
        { name: "False Eyelashes", description: "False eyelashes strip", price: 12.99, qteInStock: 80 },
        { name: "Eyelash Glue", description: "Eyelash adhesive glue", price: 8.99, qteInStock: 100 },
        { name: "Eyelash Serum", description: "Eyelash growth serum", price: 34.99, qteInStock: 50 },
        { name: "Eyelash Primer", description: "Eyelash primer base", price: 18.99, qteInStock: 65 },
        { name: "Eyelash Mascara", description: "Waterproof mascara", price: 16.99, qteInStock: 70 },
        { name: "Eyelash Liner", description: "Eyelash defining liner", price: 14.99, qteInStock: 75 },
        { name: "Eyelash Tint", description: "Eyelash tinting kit", price: 24.99, qteInStock: 55 },
        { name: "Eyelash Lift", description: "Eyelash lifting kit", price: 39.99, qteInStock: 35 },
        { name: "Eyelash Perm", description: "Eyelash perming kit", price: 34.99, qteInStock: 40 },
        { name: "Eyelash Extensions", description: "Individual eyelash extensions", price: 49.99, qteInStock: 30 },
        { name: "Eyelash Remover", description: "Eyelash glue remover", price: 12.99, qteInStock: 85 },
        { name: "Eyelash Curler", description: "Heated eyelash curler", price: 22.99, qteInStock: 60 },
        { name: "Eyelash Comb", description: "Eyelash separating comb", price: 10.99, qteInStock: 90 },
        { name: "Eyelash Brush", description: "Eyelash mascara brush", price: 8.99, qteInStock: 110 },
        { name: "Eyelash Spoolie", description: "Eyelash spoolie brush", price: 6.99, qteInStock: 130 },
        { name: "Eyelash Tool", description: "Eyelash application tool", price: 9.99, qteInStock: 100 },
        { name: "Eyelash Case", description: "Eyelash storage case", price: 7.99, qteInStock: 120 },
        { name: "Eyelash Cleaner", description: "Eyelash cleaning solution", price: 14.99, qteInStock: 75 },
        { name: "Eyelash Conditioner", description: "Eyelash conditioning treatment", price: 19.99, qteInStock: 65 },
        { name: "Eyelash Protector", description: "Eyelash protection serum", price: 24.99, qteInStock: 50 },
        { name: "Eyelash Enhancer", description: "Eyelash enhancing serum", price: 29.99, qteInStock: 45 },
        { name: "Eyelash Revitalizer", description: "Eyelash revitalizing treatment", price: 34.99, qteInStock: 40 },
        { name: "Eyelash Restorer", description: "Eyelash restoring serum", price: 39.99, qteInStock: 35 },
        { name: "Eyelash Rejuvenator", description: "Eyelash rejuvenating cream", price: 44.99, qteInStock: 30 },
        { name: "Eyelash Stimulator", description: "Eyelash stimulating serum", price: 49.99, qteInStock: 25 },
        { name: "Eyelash Activator", description: "Eyelash activating treatment", price: 54.99, qteInStock: 20 },
        { name: "Eyelash Booster", description: "Eyelash boosting serum", price: 59.99, qteInStock: 18 },
        { name: "Eyelash Fortifier", description: "Eyelash fortifying treatment", price: 64.99, qteInStock: 15 },
        { name: "Eyelash Strengthener", description: "Eyelash strengthening serum", price: 69.99, qteInStock: 12 },
        { name: "Eyelash Nourisher", description: "Eyelash nourishing oil", price: 74.99, qteInStock: 10 },
        { name: "Eyelash Moisturizer", description: "Eyelash moisturizing cream", price: 79.99, qteInStock: 8 },
        { name: "Eyelash Protector", description: "Eyelash protective coating", price: 84.99, qteInStock: 6 },
        { name: "Eyelash Shield", description: "Eyelash protective shield", price: 89.99, qteInStock: 5 },
        { name: "Eyelash Guard", description: "Eyelash protective guard", price: 94.99, qteInStock: 4 },
        { name: "Eyelash Barrier", description: "Eyelash protective barrier", price: 99.99, qteInStock: 3 },
        { name: "Eyelash Defense", description: "Eyelash defensive serum", price: 104.99, qteInStock: 2 },
        { name: "Eyelash Armor", description: "Eyelash protective armor", price: 109.99, qteInStock: 1 }
    ];

    const products = await Promise.all(
        productData.map(p => prisma.product.create({ data: p }))
    );

    // ----- Users -----
    const userData = [
        { name: "Alice Johnson", email: "alice@example.com", password: "password123", emailVerified: new Date(), address: "123 Main St, Cityville", phoneNumber: "1111111111", role: "CUSTOMER" },
        { name: "Bob Smith", email: "bob@example.com", password: "password123", emailVerified: new Date(), address: "456 Elm St, Townsville", phoneNumber: "2222222222", role: "CUSTOMER" },
        { name: "Charlie Brown", email: "charlie@example.com", password: "password123", emailVerified: new Date(), address: "789 Oak Ave, Villagetown", phoneNumber: "3333333333", role: "CUSTOMER" },
        { name: "Diana Prince", email: "diana@example.com", password: "password123", emailVerified: new Date(), address: "101 Pine Rd, Metropolis", phoneNumber: "4444444444", role: "CUSTOMER" },
        { name: "Edward Norton", email: "edward@example.com", password: "password123", emailVerified: new Date(), address: "202 Maple Ln, Gotham", phoneNumber: "5555555555", role: "CUSTOMER" },
        { name: "Fiona Green", email: "fiona@example.com", password: "password123", emailVerified: new Date(), address: "303 Birch Ct, Smallville", phoneNumber: "6666666666", role: "CUSTOMER" },
        { name: "George White", email: "george@example.com", password: "password123", address: "404 Cedar Dr, Springfield", phoneNumber: "7777777777", role: "CUSTOMER" },
        { name: "Hannah Black", email: "hannah@example.com", password: "password123", address: "505 Spruce St, Riverside", phoneNumber: "8888888888", role: "CUSTOMER" },
        { name: "Ian Gray", email: "ian@example.com", password: "password123", address: "606 Willow Way, Hilldale", phoneNumber: "9999999999", role: "CUSTOMER" },
        { name: "Julia Violet", email: "julia@example.com", password: "password123", address: "707 Aspen Pl, Brookside", phoneNumber: "0000000000", role: "CUSTOMER" },
        { name: "Kevin Orange", email: "kevin@example.com", password: "password123", address: "808 Redwood Rd, Valleytown", phoneNumber: "1112223333", role: "CUSTOMER" },
        { name: "Laura Blue", email: "laura@example.com", password: "password123", address: "909 Cypress Ln, Mountainview", phoneNumber: "2223334444", role: "CUSTOMER" },
        { name: "Michael Red", email: "michael@example.com", password: "password123", emailVerified: new Date(), address: "1001 Sycamore St, Lakeside", phoneNumber: "3334445555", role: "ADMIN" },
        { name: "Natalie Yellow", email: "natalie@example.com", password: "password123", emailVerified: new Date(), address: "1101 Palm Ave, Desertcity", phoneNumber: "4445556666", role: "ADMIN" },
        { name: "Oliver Purple", email: "oliver@example.com", password: "password123", address: "1201 Holly Dr, Forestville", phoneNumber: "5556667777", role: "CUSTOMER" },
    ];

console.log("✅ Database seeded successfully with 100 products!");
}

// Run seed
main()
    .catch(err => console.error(err))
    .finally(async () => {
        const { default: prisma } = await import('../lib/prisma.js');
        await prisma.$disconnect();
    });
